# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{totally_tabular}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joe Fiorini"]
  s.date = %q{2010-01-17}
  s.description = %q{HTML tables are a pain in the ass. Use totaly_tabular to help make creating tables a breeze!}
  s.email = %q{joe@joefiorini.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "lib/core_ext/object.rb",
     "lib/core_ext/proc.rb",
     "lib/totally_tabular.rb",
     "lib/totally_tabular/column.rb",
     "lib/totally_tabular/html_helper.rb",
     "lib/totally_tabular/row.rb",
     "lib/totally_tabular/table.rb",
     "lib/totally_tabular/table_view.rb",
     "spec/lib/core_ext/instance_exec_spec.rb",
     "spec/lib/totally_tabular/html_helper_spec.rb",
     "spec/lib/totally_tabular/table_view_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/totally_tabular_spec.rb",
     "totally_tabular.gemspec"
  ]
  s.homepage = %q{http://github.com/faithfulgeek/totally_tabular}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{DSL for creating HTML tables}
  s.test_files = [
    "spec/lib/core_ext/instance_exec_spec.rb",
     "spec/lib/totally_tabular/html_helper_spec.rb",
     "spec/lib/totally_tabular/table_view_spec.rb",
     "spec/spec_helper.rb",
     "spec/totally_tabular_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

